# Credit card fraud detection

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [4]:
# Loading the credit_card_data:
cd_data = pd.read_csv("creditcard.csv")
cd_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
cd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# Chechking that data_set has null values:
cd_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
cd_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [8]:
# legit transcation or non_legit detail in class columns:
# 1 represent the non_legit transactions:
# 0 represents the legit transactions:
cd_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
# Separating the legit and non_legit transcations:
legit = cd_data[cd_data.Class==0]
non_legit = cd_data[cd_data.Class==1]
pd.DataFrame(legit)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [10]:
pd.DataFrame(non_legit)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [11]:
print(legit.shape) # non_Fraudulent data:
print(non_legit.shape) # Fraudulent data

(284315, 31)
(492, 31)

In [12]:
# Stastical measures of the legit and non_legit data: 
ls = legit.Amount.describe()
ls

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
n_ls = non_legit.Amount.describe()
print(n_ls)

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [14]:
#comparing legit and non_legit on the basis of their mean value:
comp = cd_data.groupby('Class').mean()
comp

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [15]:
# UNDER-SAMPLING:
# Taking the n no.of values as of non_legit data from legit data:
# The data is unbalanced so we have done the under_sampling. 

legit_sample = legit.sample(n=492)
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
230604,146404.0,-1.217784,1.573868,0.172499,-0.976335,-0.233810,-0.433195,-0.139029,0.787530,0.293041,...,-0.222011,-0.537647,-0.031555,-0.464307,-0.077253,-0.287458,-0.158434,-0.195786,2.68,0
76378,56537.0,-0.126571,1.518842,1.030758,2.692972,0.861121,-0.170132,1.021944,-0.215543,-1.930665,...,0.079012,0.289764,-0.282221,-0.101514,-0.054269,0.277755,0.128651,0.138138,2.29,0
274365,165974.0,-0.393189,-0.132531,1.354247,-1.481738,-1.099649,0.800906,-0.364692,-0.574947,-0.118857,...,0.785289,-0.057588,0.171233,0.579764,-0.605837,-0.347852,0.279229,0.163015,103.98,0
219312,141678.0,2.089896,0.056843,-2.184675,-0.114763,0.640295,-1.320985,0.736173,-0.469707,-0.062342,...,0.187837,0.640841,-0.106055,-0.271116,0.452991,0.238893,-0.091228,-0.089818,15.17,0
233261,147502.0,-2.479044,2.393887,0.356457,-0.476767,-1.042225,1.592156,-3.078487,-7.287179,-0.814474,...,-3.933904,0.634384,0.380565,-0.766313,0.171437,-0.411749,-0.114787,0.088745,69.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60069,49143.0,1.190340,-0.905903,1.048080,-0.723778,-0.763938,1.543926,-1.472738,0.588153,-0.172022,...,0.425563,1.496501,0.028701,-0.887291,0.159103,0.081534,0.125769,0.010011,0.00,0
155396,105323.0,1.995237,-0.177573,-0.182025,0.526888,-0.608760,-0.681034,-0.575699,-0.134042,2.671864,...,-0.271667,-0.408275,0.367206,-0.214667,-0.409462,-0.954040,0.033033,-0.035235,2.15,0
129983,79256.0,1.202118,-0.551761,0.838115,-0.754150,-1.214074,-0.405833,-0.795355,0.226760,2.141236,...,-0.009278,0.153706,0.019517,0.039566,0.355041,-0.649725,0.096162,0.027296,1.00,0
4601,3958.0,-1.401280,-0.357026,2.853235,2.214491,-0.399420,0.525907,0.104012,0.274678,1.635444,...,-0.318998,-0.706347,0.425887,0.524124,0.215821,-0.404612,0.049065,0.109524,178.01,0
102099,68051.0,-2.752131,2.956828,-1.809535,0.453865,-0.503415,-0.432418,-0.232348,1.351757,0.139723,...,0.045671,0.637116,0.102107,-0.303660,-0.376754,-0.404418,0.370854,-0.070118,7.99,0

In [16]:
new_ds = pd.concat([legit_sample,non_legit],axis=0)
new_ds.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
230604,146404.0,-1.217784,1.573868,0.172499,-0.976335,-0.233810,-0.433195,-0.139029,0.787530,0.293041,...,-0.222011,-0.537647,-0.031555,-0.464307,-0.077253,-0.287458,-0.158434,-0.195786,2.68,0
76378,56537.0,-0.126571,1.518842,1.030758,2.692972,0.861121,-0.170132,1.021944,-0.215543,-1.930665,...,0.079012,0.289764,-0.282221,-0.101514,-0.054269,0.277755,0.128651,0.138138,2.29,0
274365,165974.0,-0.393189,-0.132531,1.354247,-1.481738,-1.099649,0.800906,-0.364692,-0.574947,-0.118857,...,0.785289,-0.057588,0.171233,0.579764,-0.605837,-0.347852,0.279229,0.163015,103.98,0
219312,141678.0,2.089896,0.056843,-2.184675,-0.114763,0.640295,-1.320985,0.736173,-0.469707,-0.062342,...,0.187837,0.640841,-0.106055,-0.271116,0.452991,0.238893,-0.091228,-0.089818,15.17,0
233261,147502.0,-2.479044,2.393887,0.356457,-0.476767,-1.042225,1.592156,-3.078487,-7.287179,-0.814474,...,-3.933904,0.634384,0.380565,-0.766313,0.171437,-0.411749,-0.114787,0.088745,69.48,0

In [17]:
new_ds.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [18]:
new_ds['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [19]:
new_ds.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,98324.376016,0.109752,0.023534,-0.099428,0.032320,-0.002958,0.003167,-0.012029,-0.090191,0.005046,...,-0.017459,0.022503,-0.024424,0.017237,0.01060,-0.015059,0.000896,-0.010215,-0.014845,90.809126
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

In [20]:
# Splitting the data into features and target values:

X = new_ds.drop(columns='Class',axis=1)
Y = new_ds['Class']

In [21]:
X
X.shape
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
230604  146404.0 -1.217784  1.573868  0.172499 -0.976335 -0.233810 -0.433195
76378    56537.0 -0.126571  1.518842  1.030758  2.692972  0.861121 -0.170132
274365  165974.0 -0.393189 -0.132531  1.354247 -1.481738 -1.099649  0.800906
219312  141678.0  2.089896  0.056843 -2.184675 -0.114763  0.640295 -1.320985
233261  147502.0 -2.479044  2.393887  0.356457 -0.476767 -1.042225  1.592156
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
230604 -0.139029  0.787530  0.293041  ...  0.054267 -0.222011 -0.537647
76378   1.021944 -0.215543 -1.930665  ...  0.182192  0.079012  0.289764
274365 -0.364692 -0.574947 -0.118857  ... -0.098589  0.785289 -0.057588
219312  0.736173 -0.469707 -0.062342  ... -0.189237  0.187837  0.640841
233261 -3.078487 -7.287179 -0.814474  ...  1.699385 -3.933904  0.634384
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
230604 -0.031555 -0.464307 -0.077253 -0.287458 -0.158434 -0.195786    2.68
76378  -0.282221 -0.101514 -0.054269  0.277755  0.128651  0.138138    2.29
274365  0.171233  0.579764 -0.605837 -0.347852  0.279229  0.163015  103.98
219312 -0.106055 -0.271116  0.452991  0.238893 -0.091228 -0.089818   15.17
233261  0.380565 -0.766313  0.171437 -0.411749 -0.114787  0.088745   69.48
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [22]:
Y

230604    0
76378     0
274365    0
219312    0
233261    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [23]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,stratify = Y,random_state=2)
print(X.shape,X_train.shape,X_test.shape)
print(Y_test.shape,Y_train.shape)

(984, 30) (787, 30) (197, 30)
(197,) (787,)

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train,Y_train)

C:\Users\Arhum\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [26]:
# testing the model and its accuracy: 

X_train_prediction = model.predict(X_train)

training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print(f"Accuracy of X_train: {training_data_accuracy} ")

Accuracy of X_train: 0.9390088945362135

In [27]:
print(f"Training_data_prediction: {X_train_prediction} ")

Training_data_prediction: [0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 1
 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 1 0 1 0 1 1 1 0 1 1 1 0
 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1
 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0
 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 0 1 0
 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 1 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1 1 1 0 0
 1 0 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1
 1 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0
 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0
 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0
 1 1 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 0 0 1
 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0
 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0
 1 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0
 1 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1
 1 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0 0 0
 1 0 0 1 0 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 1 1 0 1 1 1 0
 0 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1
 0 1 1 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0
 1 1 0 1 0 0 0 1 1 0]

In [28]:
# Now Fitting the test value:

model.fit(X_test,Y_test)

LogisticRegression()

In [29]:
# predicting the test value and checking their accuracy score: 

X_test_prediction = model.predict(X_test)
X_test_accuracy = accuracy_score(X_test_prediction,Y_test)

In [30]:
# printing the of accuracy of the test values: 
print(f"Acuuracy of X_test: {X_test_accuracy} ")

Acuuracy of X_test: 0.949238578680203

In [31]:
print(X_test_prediction)

[1 0 0 0 1 0 1 1 0 1 0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0
 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1
 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 0 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 1 0
 1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 0 1 1 1 1 1 1 0]

In [32]:
c_matrix = confusion_matrix(X_test_prediction,Y_test)
c_matrix

array([[96,  7],
       [ 3, 91]], dtype=int64)

In [33]:
predicted_data = pd.DataFrame(np.c_[X_test,Y_test,X_test_prediction])
predicted_data

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,153761.0,1.146259,1.403458,-4.159148,2.660107,-0.323217,-1.836071,-1.623740,0.259562,-1.132044,...,0.445744,-0.141136,-0.265517,0.362260,-0.416062,0.507370,0.243744,51.37,1.0,1.0
1,105323.0,1.995237,-0.177573,-0.182025,0.526888,-0.608760,-0.681034,-0.575699,-0.134042,2.671864,...,-0.408275,0.367206,-0.214667,-0.409462,-0.954040,0.033033,-0.035235,2.15,0.0,0.0
2,64181.0,1.194353,0.062194,0.535884,0.499792,-0.630294,-0.801969,-0.119318,-0.035490,-0.043088,...,-0.083086,0.024221,0.548524,0.291392,0.383481,-0.048125,0.004601,10.00,0.0,0.0
3,10944.0,1.204533,0.020640,0.911093,0.199198,-0.684808,-0.484248,-0.474027,-0.109914,1.330121,...,0.260032,-0.039386,0.385542,0.210129,1.010131,-0.086961,-0.002192,15.95,0.0,0.0
4,26833.0,-20.532751,12.373989,-23.009003,6.144821,-15.587296,-4.384491,-15.939003,13.696416,-3.948455,...,-1.466115,-0.856779,0.125777,1.402587,-0.223755,1.574249,0.469201,99.99,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,70828.0,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76,1.0,1.0
193,21046.0,-16.917468,9.669900,-23.736443,11.824990,-9.830548,-2.514829,-17.290657,1.820408,-6.264903,...,0.972755,1.241866,-1.051086,0.038009,0.672317,2.108471,-1.421243,1.00,1.0,1.0
194,67150.0,-1.824295,0.403327,-1.994122,2.756558,-3.139064,0.408185,-1.209045,1.095634,-1.447225,...,0.341727,0.947506,-0.145493,0.049326,0.831065,0.332421,0.252713,489.71,1.0,1.0
195,55614.0,-7.347955,2.397041,-7.572356,5.177819,-2.854838,-1.795239,-8.783235,0.437157,-3.740598,...,0.543325,-0.547955,-0.503722,-0.310933,-0.163986,1.197895,0.378187,0.83,1.0,1.0
196,68262.0,-1.057918,1.328342,2.118577,0.718058,-0.344530,0.099953,0.105639,0.411812,-0.315843,...,0.092131,-0.179132,0.055949,0.119011,-0.370539,-0.058056,-0.137683,2.50,0.0,0.0

In [ ]:
# --- Simple Command-Line Interface Starts Here ---

print("\n--- Credit Card Fraud Detection Test Interface ---")
print("Enter transaction details below. Type 'quit' at any prompt to exit.")

# Get the feature names in the order the model expects them
feature_names = X.columns.tolist()

while True:
    input_data_list = []
    try:
        print("\nPlease enter the following transaction features:")
        for feature in feature_names:
            user_input = input(f"  Enter value for {feature}: ")
            if user_input.lower() == 'quit':
                raise KeyboardInterrupt # Use an exception to break out cleanly

            # Attempt to convert input to float
            input_data_list.append(float(user_input))

        # Convert list to NumPy array and reshape for prediction (1 row, 30 columns)
        input_data_array = np.array(input_data_list).reshape(1, -1)

        # Make prediction
        prediction = model.predict(input_data_array)
        prediction_proba = model.predict_proba(input_data_array) # Get probabilities

        # Display result
        print("\n--- Prediction Result ---")
        if prediction[0] == 0:
            print("  Prediction: Legitimate Transaction")
        else:
            print("  Prediction: >> Fraudulent Transaction <<")

        print(f"  Probability -> [Legitimate: {prediction_proba[0][0]:.4f}, Fraudulent: {prediction_proba[0][1]:.4f}]")
        print("-------------------------\n")

    except ValueError:
        # Handle cases where input is not a valid number
        print("\nError: Invalid input. Please enter numeric values only.")
        print("Restarting transaction input...\n")
        continue # Skip rest of the loop and start asking for input again

    except KeyboardInterrupt:
        # Handle user typing 'quit'
        print("\nExiting test interface.")
        break # Exit the while loop

    except Exception as e:
        # Catch any other unexpected errors
        print(f"\nAn unexpected error occurred: {e}")
        print("Exiting test interface.")
        break

print("--- Interface Closed ---")